name: Metrics

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3 点执行
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_ID }}
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
